apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2022-02-24T08:10:03Z'
  generation: 2
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2022-02-24T08:10:03Z'
  name: dev-pipeline
  namespace: pipeline
  resourceVersion: '1234112'
  uid: 036eadd6-774e-4a96-8708-f05e0bb67515
spec:
  finally:
    - name: createroute
      params:
        - name: SCRIPT
          value: oc expose service/python-rest-service -n dev
        - name: VERSION
          value: latest
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: source
        - name: kubeconfig-dir
          workspace: source
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/likhia/python-rest-service.git'
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:af7dd5b3b1598a980f17d5f5d3d8a4b11ab4f5184677f7f17ad302baa36bd3c1
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: build
      params:
        - name: SCRIPT
          value: >-
            oc new-build  --name=python-rest-service  --binary
            --image-stream=python:latest -e APP_FILE=ws.py -n dev
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: source
        - name: kubeconfig-dir
          workspace: source
    - name: startbuild
      params:
        - name: SCRIPT
          value: oc start-build python-rest-service -n dev  --from-dir=.  --follow
        - name: VERSION
          value: latest
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: source
        - name: kubeconfig-dir
          workspace: source
    - name: deploy
      params:
        - name: SCRIPT
          value: 'oc new-app python-rest-service:latest -e APP_FILE=ws.py -n dev'
        - name: VERSION
          value: latest
      runAfter:
        - startbuild
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: source
        - name: kubeconfig-dir
          workspace: source
  workspaces:
    - name: source
