apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  creationTimestamp: '2022-03-02T05:53:54Z'
  generation: 2
  managedFields:
    - apiVersion: tekton.dev/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:finally': {}
          'f:params': {}
          'f:resources': {}
          'f:tasks': {}
          'f:workspaces': {}
      manager: Mozilla
      operation: Update
      time: '2022-03-02T05:53:54Z'
  name: staging-pipeline
  namespace: pipeline
  resourceVersion: '10553535'
  uid: 00d19ec9-619b-4c9e-8923-105684a56e7f
spec:
  params:
    - default: staging
      name: namespace
      type: string
    - default: 'https://github.com/likhia/python-rest-service.git'
      name: git-project
      type: string
    - default: python-rest-service
      name: app-name
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-project)
        - name: revision
          value: main
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:af7dd5b3b1598a980f17d5f5d3d8a4b11ab4f5184677f7f17ad302baa36bd3c1
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: staging-source
        - name: ssh-directory
          workspace: staging-source
    - name: createbuild
      params:
        - name: SCRIPT
          value: oc apply -f $(params.namespace)-build-config.yaml
        - name: VERSION
          value: latest
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: staging-source
        - name: kubeconfig-dir
          workspace: staging-source
    - name: build
      params:
        - name: SCRIPT
          value: >-
            oc start-build $(params.app-name)   --from-dir=.  --follow -n
            $(params.namespace)
        - name: VERSION
          value: latest
      runAfter:
        - createbuild
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: staging-source
        - name: kubeconfig-dir
          workspace: staging-source
    - name: deployment
      params:
        - name: SCRIPT
          value: oc apply -f $(params.namespace)-deployment.yaml
        - name: VERSION
          value: latest
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: staging-source
        - name: kubeconfig-dir
          workspace: staging-source
    - name: service
      params:
        - name: SCRIPT
          value: oc apply -f $(params.namespace)-service.yaml
        - name: VERSION
          value: latest
      runAfter:
        - deployment
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: staging-source
        - name: kubeconfig-dir
          workspace: staging-source
    - name: route
      params:
        - name: SCRIPT
          value: 'oc apply -f $(params.namespace)-route.yaml '
        - name: VERSION
          value: latest
      runAfter:
        - service
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: staging-source
        - name: kubeconfig-dir
          workspace: staging-source
  workspaces:
    - name: staging-source
